### ISSUE TITLE
Error when clicking accept/deny

### ISSUE THREAD

**Issue by lstocchi** [redhat-developer/intellij-redhat-telemetry#10]
I'm getting this NPE when trying to click accept/deny. `Later` is working fine 
```
java.lang.NullPointerException
	at com.redhat.devtools.intellij.telemetry.core.configuration.TelemetryConfiguration.put(TelemetryConfiguration.java:76)
	at com.redhat.devtools.intellij.telemetry.core.configuration.TelemetryConfiguration.setMode(TelemetryConfiguration.java:51)
	at com.redhat.devtools.intellij.telemetry.core.configuration.TelemetryConfiguration.setEnabled(TelemetryConfiguration.java:63)
	at com.redhat.devtools.intellij.telemetry.ui.TelemetryNotifications.enableTelemetry(TelemetryNotifications.java:68)
	at com.redhat.devtools.intellij.telemetry.ui.TelemetryNotifications.lambda$queryUserConsent$0(TelemetryNotifications.java:53)
	at com.intellij.openapi.project.DumbAwareAction$SimpleDumbAwareAction.actionPerformed(DumbAwareAction.java:59)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:266)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:283)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAwareWithCallbacks(ActionUtil.java:257)
	at com.intellij.notification.Notification.fire(Notification.java:237)
	at com.intellij.notification.impl.NotificationsManagerImpl$12.linkSelected(NotificationsManagerImpl.java:736)
	at com.intellij.notification.impl.NotificationsManagerImpl$12.linkSelected(NotificationsManagerImpl.java:733)
	at com.intellij.ui.components.labels.LinkLabel.doClick(LinkLabel.java:142)
	at com.intellij.ui.components.labels.LinkLabel.doClick(LinkLabel.java:356)
	at com.intellij.ui.components.labels.LinkLabel$MyMouseHandler.mouseReleased(LinkLabel.java:330)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6651)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6416)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5026)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4858)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2773)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4858)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:906)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:844)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:776)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:422)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:698)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:421)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by adietish** [comment]
I can confirm this, unfortunately. Thanks for reporting.

**Comment by adietish** [comment]
Fixing this I found out that there's another additional bug at work:

`build.gradle` sets the telemetry mode to `DEBUG` so when checking if telemetry is configured, the answer is yes, it's set to `DEBUG`. This means that you should not get asked if you want to "Accep" or "Deny" telemetry.

I found out about this bug and fixed it when writing the tests at: https://github.com/redhat-developer/intellij-redhat-telemetry/pull/9

**Comment by adietish** [comment]
The proper reason for this NPE is the sequence in which static variables are initialized: I statically initialize a variable that holds the IJ notification bus. I pass it along via the constructor so that unit tests can provide mocks instead. `TelemetryConfiguration` is a singleton and thus statically constructed too. It turns out that the sequence in which static variables are initialized is creating the singleton (`public static final`) before the notification bus (`private static final`). This then causes the NPE when the notification bus is to be used.

**Comment by adietish** [comment]
to enable being asked you can simply change `build.gradle` to the following (empty mode string or any undefined value like `bogus`, `luky luke`, `darth vader lost his helmet`):

```
runIde {
    systemProperties['com.redhat.devtools.intellij.telemetry.mode'] = ''
}
```
