### ISSUE TITLE
1.1.0 breaks consuming plugins

### ISSUE THREAD

**Issue by coppolaop** [redhat-developer/intellij-redhat-telemetry#79]
Last update makes my intellij break all quarkus APIs. I can't run it anymore.

> java.lang.NoSuchMethodError: 'com.redhat.devtools.intellij.telemetry.core.service.TelemetryMessageBuilder$Message com.redhat.devtools.intellij.telemetry.core.service.TelemetryMessageBuilder$ActionMessage.property(java.lang.String, java.lang.String)'
	at com.redhat.devtools.intellij.quarkus.run.QuarkusRunConfiguration.getState(QuarkusRunConfiguration.java:127)
	at com.intellij.execution.runners.ExecutionEnvironment.getState(ExecutionEnvironment.java:218)
	at com.intellij.execution.impl.DefaultJavaProgramRunner.execute(DefaultJavaProgramRunner.java:94)
	at com.intellij.execution.impl.ExecutionManagerImpl.executeConfiguration(ExecutionManagerImpl.kt:804)
	at com.intellij.execution.impl.ExecutionManagerImpl.access$executeConfiguration(ExecutionManagerImpl.kt:78)
	at com.intellij.execution.impl.ExecutionManagerImpl$executeConfiguration$1$2.invoke(ExecutionManagerImpl.kt:737)
	at com.intellij.execution.impl.ExecutionManagerImpl$executeConfiguration$1$2.invoke(ExecutionManagerImpl.kt:733)
	at com.intellij.execution.impl.ExecutionManagerImpl.executeConfiguration$lambda$13$lambda$12(ExecutionManagerImpl.kt:733)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$safeTransferToEdt$7(NonBlockingReadActionImpl.java:717)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:22)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:843)
	at com.intellij.openapi.application.impl.ApplicationImpl$4.run(ApplicationImpl.java:463)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithEnabledImplicitRead(RwLockHolder.kt:75)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithImplicitRead(RwLockHolder.kt:67)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWithImplicitRead(ApplicationImpl.java:1436)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:82)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:124)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:44)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:792)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:733)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:761)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:695)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$12(IdeEventQueue.kt:589)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithoutImplicitRead(RwLockHolder.kt:44)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:589)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:72)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:355)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:354)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:793)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:354)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:1014)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1014)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:349)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:848)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:391)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

**Comment by leduardobc** [comment]
Same here.

Ubuntu 22.04.3 LTS
Intellij 2023.2.5 (Community Edition)
Quarkus Tools 1.30.0
Telemetry by Red hat 1.1.0.52
Java 17 zulu
maven 3.9.0

I have tried to reinstall both plugins, Invalidate caches and repair IDE.  Nothing worked. :(

**Comment by jsantaelena** [comment]
Same here too. 
I solved downloading the precious version and reinstalling it from disk (there is a option in intellij for that).

**Comment by tibersept** [comment]
Same here.

MacOS Sonoma 14.2.1
IntelliJ IDEA 2023.3.2 (Community Edition)
Build #IC-233.13135.103, built on December 20, 2023
Quarkus Tools 1.30.0
Telemetry by Red Hat 1.1.0.52

**Comment by jsantaelena** [comment]
By the way, the Quarkus Tools also works quite differently in debug mode.
Without the Wuarkus Tools plugin when you launchs the application from the
services window you get debug and console at the same window, which is more
productive than having to switch from services to debug windows while you
advance with debug steps.

I have uninstalled both telemetry and quarkus tools plugins until it gets a
bit mature.

**Comment by angelozerr** [comment]
We ned to fix that, but for the moment please read https://github.com/redhat-developer/intellij-quarkus/issues/1301#issuecomment-1870161138

> By the way, the Quarkus Tools also works quite differently in debug mode.
Without the Wuarkus Tools plugin when you launchs the application from the
services window you get debug and console at the same window, which is more
productive than having to switch from services to debug windows while you
advance with debug steps

Could you create an issue at https://github.com/redhat-developer/intellij-quarkus/issues please. 

I suspect that you use Intellij Ultimate which provides Quarkus run configuration, right?

**Comment by jsantaelena** [comment]
Thanks for replying.

[Issue raised.](https://github.com/redhat-developer/intellij-quarkus/issues/1303#issue-2062411206)

**Comment by adietish** [comment]
The latest evolution of this plugin is API compatible but apparently not binary compatible. It is causing the consuming plugins (quarkus, kubernetes, openshift, ...) to break with the above message :(
The fix(es) are to be done in the consuming plugins:
* https://github.com/redhat-developer/intellij-quarkus/pull/1304
* https://github.com/redhat-developer/intellij-openshift-connector/pull/649
* https://github.com/redhat-developer/intellij-rsp/issues/157
* https://github.com/redhat-developer/intellij-kubernetes/issues/693

**Comment by adietish** [comment]
all consumers merged and publised to marketplace (all but intellij-rsp which needs to be published). Closing.
